In [1]:
import torch 
x = torch.tensor([1, 2, 3, 4])
torch.unsqueeze(x, 0)
torch.unsqueeze(x, 1)

tensor([[1],
        [2],
        [3],
        [4]])

In [11]:
y = torch.tensor([[0, 12, 434, 5], [0, 5, 6, 7]])
z = torch.unsqueeze(y, 0)


In [12]:
print(y.shape)

torch.Size([2, 4])


In [13]:
print(z.shape)

torch.Size([1, 2, 4])


In [14]:
print(z)

tensor([[[  0,  12, 434,   5],
         [  0,   5,   6,   7]]])


In [15]:
print(y.unsqueeze(1).shape)

torch.Size([2, 1, 4])


In [16]:
y.unsqueeze(1)

tensor([[[  0,  12, 434,   5]],

        [[  0,   5,   6,   7]]])

In [2]:
from collections import namedtuple, deque
capacity = 5 
memory = deque([], maxlen=capacity)

In [4]:
for i in range(20): 
    memory.append(i)
    print(memory)

deque([0], maxlen=5)
deque([0, 1], maxlen=5)
deque([0, 1, 2], maxlen=5)
deque([0, 1, 2, 3], maxlen=5)
deque([0, 1, 2, 3, 4], maxlen=5)
deque([1, 2, 3, 4, 5], maxlen=5)
deque([2, 3, 4, 5, 6], maxlen=5)
